spring:
  application:
    name: Place
  cloud:
    config:
      profile: local
  config:
    import: "configserver:${configurl}"
  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: kafka-topic


configurl: http://localhost:8079