spring:
  application:
    name: Place
  cloud:
    config:
      profile: prod
  config:
    import: "configserver:${configurl}"
  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: kafka-topic


management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true

configurl: http://configserver:8079
