spring:
  application:
    name: FavoritePlace
  data:
    mongodb:
      uri: mongodb://localhost:27017/favoriteplacedb
  cloud:
    config:
      profile: prod
  config:
    import: "configserver:${configurl}"

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
configurl: http://configserver:8079


