spring:
  application:
    name: FavoritePlace
  data:
    mongodb:
      uri: mongodb://localhost:27017/favoriteplacedb
  cloud:
    config:
      profile: local
  config:
    import: "configserver:${configurl}"


configurl: http://localhost:8079


