spring:
  application:
    name: Search
  data:
    elasticsearch:
      rest:
        uris: http://elasticsearch:9200
  cloud:
    config:
      profile: local
  config:
    import: "configserver:${configurl}"

configurl: http://localhost:8079