spring.application.name=Search
spring.cloud.config.profile=prod
spring.config.import=configserver:${configurl}/

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always

configurl=http://configserver:8079
